// alive/scripts/lifecycle/heartbeat-outreach.ts
// Proactive message sending from heartbeat — sends natural in-character messages
// to the user via OpenClaw `message send`.
//
// Design principles:
// - Conservative by default: sends at most 2 messages per day
// - Time-aware: respects quiet hours and persona time-of-day behavior
// - Fail-safe: never throws; failures degrade to diary/log only
// - Persona-aligned: message content generated by LLM with full voice directive

import { execFileSync } from 'child_process';
import { PATHS, readJSON, writeJSON, readTemplate, appendText } from '../utils/file-utils';
import { callLLMJSON } from '../utils/llm-client';
import { getLocalHour, getLocalDate, getLocalTimeHHMM, now } from '../utils/time-utils';
import type { EmotionState } from '../utils/types';

// ── Configuration ─────────────────────────────────────────────────

import { OUTREACH_CONFIG } from '../config';

/** Max proactive messages per calendar day */
const MAX_DAILY_OUTREACH = OUTREACH_CONFIG.MAX_DAILY_OUTREACH;

/** Minimum hours between two proactive messages */
const COOLDOWN_HOURS = OUTREACH_CONFIG.COOLDOWN_HOURS;

/** Hours where proactive messages are allowed (inclusive) */
const ACTIVE_HOURS = OUTREACH_CONFIG.ACTIVE_HOURS;

/** Minimum sociability threshold to consider sending */
const MIN_SOCIABILITY = OUTREACH_CONFIG.MIN_SOCIABILITY;

/** Minimum valence — don't message when very upset */
const MIN_VALENCE = OUTREACH_CONFIG.MIN_VALENCE;

// ── State type ────────────────────────────────────────────────────

export interface OutreachState {
  date: string;
  count: number;
  last_sent_at: string | null;
  last_message: string | null;
}

export const DEFAULT_OUTREACH: OutreachState = {
  date: '',
  count: 0,
  last_sent_at: null,
  last_message: null,
};

// ── Path helper (co-located with memory base) ─────────────────────

function getOutreachStatePath(): string {
  // Piggyback on PATHS pattern — lives alongside other memory files
  return PATHS.outboundHistory.replace('outbound-history.json', 'outreach-state.json');
}

// ── Gate checks ───────────────────────────────────────────────────

export interface OutreachGateInput {
  hour: number;
  emotion: EmotionState;
  outreachState: OutreachState;
  todayStr: string;
  currentTimeISO: string;
}

export interface OutreachGateResult {
  allowed: boolean;
  reason: string;
}

/**
 * Check all gate conditions for proactive messaging.
 * Returns { allowed, reason }.
 */
export function checkOutreachGate(input: OutreachGateInput): OutreachGateResult {
  const { hour, emotion, outreachState, todayStr, currentTimeISO } = input;

  // Time window
  if (hour < ACTIVE_HOURS.start || hour > ACTIVE_HOURS.end) {
    return { allowed: false, reason: `quiet-hours (${hour}h, active ${ACTIVE_HOURS.start}-${ACTIVE_HOURS.end})` };
  }

  // Daily limit
  const dailyCount = outreachState.date === todayStr ? outreachState.count : 0;
  if (dailyCount >= MAX_DAILY_OUTREACH) {
    return { allowed: false, reason: `daily-limit (${dailyCount}/${MAX_DAILY_OUTREACH})` };
  }

  // Cooldown
  if (outreachState.last_sent_at) {
    const elapsedMs = new Date(currentTimeISO).getTime() - new Date(outreachState.last_sent_at).getTime();
    const elapsedHours = elapsedMs / (1000 * 60 * 60);
    if (elapsedHours < COOLDOWN_HOURS) {
      return { allowed: false, reason: `cooldown (${elapsedHours.toFixed(1)}h < ${COOLDOWN_HOURS}h)` };
    }
  }

  // Emotion gates
  if (emotion.sociability < MIN_SOCIABILITY) {
    return { allowed: false, reason: `low-sociability (${emotion.sociability.toFixed(2)} < ${MIN_SOCIABILITY})` };
  }
  if (emotion.mood.valence < MIN_VALENCE) {
    return { allowed: false, reason: `low-valence (${emotion.mood.valence.toFixed(2)} < ${MIN_VALENCE})` };
  }

  return { allowed: true, reason: 'ok' };
}

// ── Message generation ────────────────────────────────────────────

interface ProactiveMessageInput {
  actionDescription: string;
  innerMonologue: string;
  emotionSummary: string;
  voiceDirective: string;
  recentDiary: string;
  hour: number;
}

interface ProactiveMessageOutput {
  should_send: boolean;
  message: string;
  reason: string;
}

/**
 * Ask LLM whether this action warrants messaging the user,
 * and if so, generate the message in persona voice.
 */
export async function generateProactiveMessage(
  input: ProactiveMessageInput,
): Promise<ProactiveMessageOutput> {
  const template = readTemplate('outreach-message-prompt.md');
  const prompt = template
    .replace('{action_description}', input.actionDescription)
    .replace('{inner_monologue}', input.innerMonologue)
    .replace('{emotion_summary}', input.emotionSummary)
    .replace('{voice_directive}', input.voiceDirective)
    .replace('{recent_diary}', input.recentDiary)
    .replace('{hour}', String(input.hour));

  return callLLMJSON<ProactiveMessageOutput>(prompt, undefined, 'heartbeat-outreach');
}

// ── Send ──────────────────────────────────────────────────────────

/**
 * Send a text message via OpenClaw CLI.
 * Returns true on success, false on failure (never throws).
 */
export function sendMessageViaOpenClaw(message: string): boolean {
  try {
    execFileSync('openclaw', ['message', 'send', '--message', message], {
      timeout: 15_000,
      encoding: 'utf8',
    });
    return true;
  } catch (err) {
    console.error(`[outreach] openclaw message send failed: ${(err as Error).message}`);
    return false;
  }
}

// ── Main orchestrator ─────────────────────────────────────────────

export interface OutreachContext {
  actionDescription: string;
  innerMonologue: string;
  emotion: EmotionState;
  voiceDirective: string;
  recentDiary: string;
}

export interface OutreachResult {
  attempted: boolean;
  sent: boolean;
  message: string | null;
  reason: string;
}

/**
 * Full outreach pipeline: gate check → LLM generation → send → state update.
 * Safe to call on every heartbeat tick — gate logic ensures proper throttling.
 *
 * **Never throws.** All failures are caught and returned in the result.
 */
export async function attemptProactiveOutreach(ctx: OutreachContext): Promise<OutreachResult> {
  const currentTime = now();
  const hour = getLocalHour(currentTime);
  const todayStr = getLocalDate(currentTime);
  const currentTimeISO = currentTime.toISOString();
  const timeStr = getLocalTimeHHMM(currentTime);

  // 1. Read state
  const statePath = getOutreachStatePath();
  let outreachState = readJSON<OutreachState>(statePath, DEFAULT_OUTREACH);

  // 2. Gate check
  const gate = checkOutreachGate({
    hour,
    emotion: ctx.emotion,
    outreachState,
    todayStr,
    currentTimeISO,
  });

  if (!gate.allowed) {
    console.log(`[outreach] Gate blocked: ${gate.reason}`);
    return { attempted: false, sent: false, message: null, reason: gate.reason };
  }

  // 3. LLM: should we send? what to say?
  let llmResult: ProactiveMessageOutput;
  try {
    const emotionSummary = `${ctx.emotion.mood.description} (v:${ctx.emotion.mood.valence.toFixed(1)} a:${ctx.emotion.mood.arousal.toFixed(1)} e:${ctx.emotion.energy.toFixed(1)} soc:${ctx.emotion.sociability.toFixed(1)})`;
    llmResult = await generateProactiveMessage({
      actionDescription: ctx.actionDescription,
      innerMonologue: ctx.innerMonologue,
      emotionSummary,
      voiceDirective: ctx.voiceDirective,
      recentDiary: ctx.recentDiary,
      hour,
    });
  } catch (err) {
    console.error(`[outreach] LLM generation failed: ${(err as Error).message}`);
    return { attempted: true, sent: false, message: null, reason: `llm-error: ${(err as Error).message}` };
  }

  if (!llmResult.should_send) {
    console.log(`[outreach] LLM decided not to send: ${llmResult.reason}`);
    return { attempted: true, sent: false, message: null, reason: `llm-skip: ${llmResult.reason}` };
  }

  // 4. Send
  const sent = sendMessageViaOpenClaw(llmResult.message);

  // 5. Update state (whether or not send succeeded — prevent rapid retry)
  outreachState = {
    date: todayStr,
    count: (outreachState.date === todayStr ? outreachState.count : 0) + 1,
    last_sent_at: currentTimeISO,
    last_message: llmResult.message,
  };
  try {
    writeJSON(statePath, outreachState);
  } catch (err) {
    console.error(`[outreach] State write failed: ${(err as Error).message}`);
  }

  // 6. Diary entry
  if (sent) {
    try {
      appendText(PATHS.diary, `\n## ${todayStr} ${timeStr}\n主动给朋友发了消息：「${llmResult.message.slice(0, 60)}」\n情绪: ${ctx.emotion.mood.description} | 重要性: 3\n标签: outreach, 社交\n`);
    } catch { /* best effort */ }
    console.log(`[outreach] Sent: ${llmResult.message.slice(0, 80)}`);
  } else {
    try {
      appendText(PATHS.diary, `\n## ${todayStr} ${timeStr}\n想发消息但是没发出去...\n情绪: ${ctx.emotion.mood.description} | 重要性: 2\n标签: outreach-fail\n`);
    } catch { /* best effort */ }
    console.log(`[outreach] Send failed, message: ${llmResult.message.slice(0, 80)}`);
  }

  return {
    attempted: true,
    sent,
    message: llmResult.message,
    reason: sent ? 'sent' : 'send-failed',
  };
}
